name: Upload website to S3a

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated to the latest version
      - name: Install Dependencies
        run: |
          npm install  # If using Node.js, adjust for your project's dependencies
      - name: Build Project
        run: |
          npm run build  # Adjust if your build script is different
      - uses: jakejarvis/s3-sync-action@v0.5.3  # Updated to the latest version
        with:
          args: --follow-symlinks --delete  # Removed --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ca-central-1'
          SOURCE_DIR: 'Portfolio Website'  # Adjust to your build output directory
      - name: Invalidate CloudFront Cache (Optional)
        uses: chetan/invalidate-cloudfront-action@v1.5
        with:
          distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ca-central-1'
