name: Invalidate CloudFront Cache

on:
  workflow_run:
    workflows: ["Upload website to S3 bucket"]
    types:
      - completed

jobs:
  invalidate-cache:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Invalidate CloudFront Cache
        uses: aws-actions/aws-cloudfront-invalidate-cache@v1
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ca-central-1'
